# Generated by Django 4.1.3 on 2023-01-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('contact', models.IntegerField(max_length=225, unique=True)),
                ('location', models.EmailField(max_length=225)),
            ],
        ),
    ]
